[package]
name = "nsis-process"
version = "0.4.2"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
crate-type = [ "cdylib" ]

[features]
test = [ ]

[dependencies]
nsis-plugin-api = { workspace = true }
windows-sys = { workspace = true }
